# Generated by Django 4.1.6 on 2023-02-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('blog1', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
    ]
