# Generated by Django 4.1.6 on 2023-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
